version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/webapp/"
    schedule:
      interval: "weekly"
      day: tuesday
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: tuesday