version: "3"

x-logging:
  &default-logging
  driver: "json-file"
  options: 
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  api:
    build:
      context: ../src
      dockerfile: ./cmd/api/Dockerfile
    container_name: api
    ports:
      - "4444:4444"
    environment:
      DEV_MODE: "true"
      RABBITMQ_ADDR: "rabbitmq:5672"
      RABBITMQ_USER: "guest"
      RABBITMQ_PWD: "guest"
      S3_HOST: "http://s3:9000"
      S3_AUTH_KEY: "admin"
      S3_AUTH_PWD: "password"
      USER_AUTH: "dev"
      PWD_AUTH: "test"
    logging:
      *default-logging
    depends_on:
      rabbitmq:
        condition: service_healthy
      s3:
        condition: service_healthy

  encoder:
    build:
      context: ../src
      dockerfile: ./cmd/encoder/Dockerfile
    container_name: encoder
    environment:
      DEV_MODE: "true"
      RABBITMQ_ADDR: "rabbitmq:5672"
      RABBITMQ_USER: "guest"
      RABBITMQ_PWD: "guest"
      S3_HOST: "http://s3:9000"
      S3_AUTH_KEY: "admin"
      S3_AUTH_PWD: "password"
    logging:
      *default-logging
    depends_on:
      rabbitmq:
        condition: service_healthy
      s3:
        condition: service_healthy
