version: "3"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  api:
    build:
      context: ../src
      dockerfile: ./cmd/api/Dockerfile
    container_name: api
    ports:
      - "4444:4444"
    environment:
      DEV_MODE: ${DEV_MODE}
      RABBITMQ_ADDR: ${RABBITMQ_ADDR}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
      S3_HOST: ${S3_HOST}
      S3_AUTH_KEY: ${S3_AUTH_KEY}
      S3_AUTH_PWD: ${S3_AUTH_PWD}
      USER_AUTH: ${USER_AUTH}
      PWD_AUTH: ${PWD_AUTH}
    logging:
      *default-logging
    depends_on:
      rabbitmq:
        condition: service_healthy
      s3:
        condition: service_healthy

  encoder:
    build:
      context: ../src
      dockerfile: ./cmd/encoder/Dockerfile
    container_name: encoder
    environment:
      DEV_MODE: ${DEV_MODE}
      RABBITMQ_ADDR: ${RABBITMQ_ADDR}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
      S3_HOST: ${S3_HOST}
      S3_AUTH_KEY: ${S3_AUTH_KEY}
      S3_AUTH_PWD: ${S3_AUTH_PWD}
    logging:
      *default-logging
    depends_on:
      rabbitmq:
        condition: service_healthy
      s3:
        condition: service_healthy
