version: "3"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  s3:
    image: minio/minio:RELEASE.2022-02-05T04-40-59Z@sha256:81c909777dabe47293614d3664cf328c75303e53e451ad6214aac6ff56de1b60
    container_name: s3
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_AUTH_KEY}
      MINIO_ROOT_PASSWORD: ${S3_AUTH_PWD}
    logging:
      *default-logging
    command: server --console-address ":9001" /home/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - .data/minio:/home/shared

  rabbitmq:
    image: rabbitmq:3.9-management@sha256:0fec1b1e2345ffa7d8c1e4882e33fef79576f376db8e419a3b3ad021e772b362
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PWD}
    logging:
      *default-logging
    healthcheck:
      test: rabbitmq-diagnostics -q alarms
      interval: 30s
      timeout: 30s
      retries: 3

  mariadb:
    image: mariadb:10.5@sha256:223494f1d9b4a7bcc19c8ae4e45628d303be36ed711a967f0720465f8615d324
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mariadb:/var/lib/mysql/
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "--password=${MARIADB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 20s
      retries: 3

  consul:
    image: consul:1.12@sha256:a1a933572cb6f6388501c535af455f77e687c62ff97ed72cd16301b8b535eae0
    container_name: consul
    volumes:
      - ./.consul.d/:/consul/config/
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
