version: "3"

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  grafana:
    image: grafana/grafana:8.4.3@sha256:44ea09598b05bd6296f663bb728eb6af90f45399648d85b4123bbc3f271a121b
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./.grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=${GF_AUTH_DISABLE_LOGIN_FORM}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:main-87ddaa0@sha256:7bba7c14c95755f1e6b0a5ba67d46d341cefe0412eb5a9e1f963c4115ee1c325
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./.loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:main-87ddaa0@sha256:324fdbe7c47f1c582716e92ad8de53f4e0a1b21c4e1c145cd16885fd1829cbae
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - ./.promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  node-exporter:
    image: prom/node-exporter:v1.3.1@sha256:d5b2a2e2bb07a4a5a7c4bd9e54641cab63e1d2627622dbde17efc04849d3d30d
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:v2.33.4@sha256:35337321e0e7d8c62b5035b712f895170fe2ec42d3181f0d46a7d1af3dfdb1d4
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./.prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
