version: "3"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  s3:
    image: minio/minio:RELEASE.2022-02-05T04-40-59Z@sha256:81c909777dabe47293614d3664cf328c75303e53e451ad6214aac6ff56de1b60
    container_name: s3
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    logging:
      *default-logging
    command: server --console-address ":9001" /home/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - .data/minio:/home/shared

  rabbitmq:
    image: rabbitmq:3.9-management@sha256:0fec1b1e2345ffa7d8c1e4882e33fef79576f376db8e419a3b3ad021e772b362
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    logging:
      *default-logging
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mariadb:/var/lib/mysql/
      - ./.mariadb/.schema/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "passwordroot"
      MYSQL_DATABASE: "voogle-database"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "guest"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 20s
      retries: 3
