version: "3"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  api:
    build:
      context: ../src
      dockerfile: ./cmd/api/Dockerfile
    container_name: api
    ports:
      - "4444:4444"
    environment:
      DEV_MODE: ${DEV_MODE}
      RABBITMQ_ADDR: ${RABBITMQ_ADDR}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
      S3_HOST: ${S3_HOST}
      S3_AUTH_KEY: ${S3_AUTH_KEY}
      S3_AUTH_PWD: ${S3_AUTH_PWD}
      USER_AUTH: ${USER_AUTH}
      PWD_AUTH: ${PWD_AUTH}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      GRAY_TRANSFORMER_ADDR: ${GRAY_TRANSFORMER_ADDR}
      FLIP_TRANSFORMER_ADDR: ${FLIP_TRANSFORMER_ADDR}
    logging:
      *default-logging
    depends_on:
      rabbitmq:
        condition: service_healthy
      s3:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      grayserver:
        condition: service_started
      flipserver:
        condition: service_started


  encoder:
    build:
      context: ../src
      dockerfile: ./cmd/encoder/Dockerfile
    container_name: encoder
    environment:
      DEV_MODE: ${DEV_MODE}
      RABBITMQ_ADDR: ${RABBITMQ_ADDR}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
      S3_HOST: ${S3_HOST}
      S3_AUTH_KEY: ${S3_AUTH_KEY}
      S3_AUTH_PWD: ${S3_AUTH_PWD}
    logging:
      *default-logging
    depends_on:
      rabbitmq:
        condition: service_healthy
      s3:
        condition: service_healthy

  grayserver:
    build:
      context: ../src
      dockerfile: ./cmd/grayserver/Dockerfile
    container_name: grayserver
    environment:
      DEV_MODE: ${DEV_MODE}
      GRAY_TRANSFORMER_ADDR: ${GRAY_TRANSFORMER_ADDR}
      RABBITMQ_ADDR: ${RABBITMQ_ADDR}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
      S3_HOST: ${S3_HOST}
      S3_AUTH_KEY: ${S3_AUTH_KEY}
      S3_AUTH_PWD: ${S3_AUTH_PWD}
    logging:
      *default-logging
    depends_on:
      s3:
        condition: service_healthy

  flipserver:
    build:
      context: ../src
      dockerfile: ./cmd/flipserver/Dockerfile
    container_name: flipserver
    environment:
      DEV_MODE: ${DEV_MODE}
      FLIP_TRANSFORMER_ADDR: ${FLIP_TRANSFORMER_ADDR}
      RABBITMQ_ADDR: ${RABBITMQ_ADDR}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
      S3_HOST: ${S3_HOST}
      S3_AUTH_KEY: ${S3_AUTH_KEY}
      S3_AUTH_PWD: ${S3_AUTH_PWD}
    logging:
      *default-logging
    depends_on:
      s3:
        condition: service_healthy