// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: v1/transformer.proto

package transformer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The path of the video on S3.
	Videopath       string   `protobuf:"bytes,1,opt,name=videopath,proto3" json:"videopath,omitempty"`
	TransformerList []string `protobuf:"bytes,2,rep,name=transformer_list,json=transformerList,proto3" json:"transformer_list,omitempty"`
}

func (x *TransformVideoRequest) Reset() {
	*x = TransformVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_transformer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformVideoRequest) ProtoMessage() {}

func (x *TransformVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transformer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformVideoRequest.ProtoReflect.Descriptor instead.
func (*TransformVideoRequest) Descriptor() ([]byte, []int) {
	return file_v1_transformer_proto_rawDescGZIP(), []int{0}
}

func (x *TransformVideoRequest) GetVideopath() string {
	if x != nil {
		return x.Videopath
	}
	return ""
}

func (x *TransformVideoRequest) GetTransformerList() []string {
	if x != nil {
		return x.TransformerList
	}
	return nil
}

type TransformVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The video part, as byte array.
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *TransformVideoResponse) Reset() {
	*x = TransformVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_transformer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformVideoResponse) ProtoMessage() {}

func (x *TransformVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_transformer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformVideoResponse.ProtoReflect.Descriptor instead.
func (*TransformVideoResponse) Descriptor() ([]byte, []int) {
	return file_v1_transformer_proto_rawDescGZIP(), []int{1}
}

func (x *TransformVideoResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_v1_transformer_proto protoreflect.FileDescriptor

var file_v1_transformer_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x6b, 0x67, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x60, 0x0a, 0x15, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x16,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x32, 0x81, 0x01, 0x0a,
	0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x29, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2a, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53,
	0x6f, 0x67, 0x69, 0x6c, 0x69, 0x73, 0x2f, 0x56, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_transformer_proto_rawDescOnce sync.Once
	file_v1_transformer_proto_rawDescData = file_v1_transformer_proto_rawDesc
)

func file_v1_transformer_proto_rawDescGZIP() []byte {
	file_v1_transformer_proto_rawDescOnce.Do(func() {
		file_v1_transformer_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_transformer_proto_rawDescData)
	})
	return file_v1_transformer_proto_rawDescData
}

var file_v1_transformer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_transformer_proto_goTypes = []interface{}{
	(*TransformVideoRequest)(nil),  // 0: pkg.transformer.v1.TransformVideoRequest
	(*TransformVideoResponse)(nil), // 1: pkg.transformer.v1.TransformVideoResponse
}
var file_v1_transformer_proto_depIdxs = []int32{
	0, // 0: pkg.transformer.v1.TransformerService.TransformVideo:input_type -> pkg.transformer.v1.TransformVideoRequest
	1, // 1: pkg.transformer.v1.TransformerService.TransformVideo:output_type -> pkg.transformer.v1.TransformVideoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_transformer_proto_init() }
func file_v1_transformer_proto_init() {
	if File_v1_transformer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_transformer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_transformer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_transformer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_transformer_proto_goTypes,
		DependencyIndexes: file_v1_transformer_proto_depIdxs,
		MessageInfos:      file_v1_transformer_proto_msgTypes,
	}.Build()
	File_v1_transformer_proto = out.File
	file_v1_transformer_proto_rawDesc = nil
	file_v1_transformer_proto_goTypes = nil
	file_v1_transformer_proto_depIdxs = nil
}
