global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090", "node-exporter:9100"]
  - job_name: "api"
    scrape_interval: 5s
    static_configs:
      - targets: ["api:4444"]
  - job_name: "rabbitmq"
    scrape_interval: 5s
    static_configs:
      - targets: ["rabbitmq:15692"]
