linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - exhaustive
    - gochecknoinits
    - gofmt
    - nakedret
    - goimports
    - nilnil
    - nilerr
    - gomoddirectives
    - cyclop

linters-settings:
  cyclop:
    max-complexity: 16