name: CI unit tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.0"
      - name: Api lint
        working-directory: services/api/
        run: make lint_ci
      - name: Api test
        working-directory: services/api/
        run: make test
