name: CI-unit-tests

on: [push]

jobs:
  CI-api-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        name: API lint
        with:
          version: v1.29
          working-directory: services/api/
      - uses: actions/setup-go@v2
        name: Install golang 1.17.0
        with:
          go-version: "^1.17.0"
      - run: make test
        name: API unit tests
        working-directory: services/api/
  CI-webapp-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
        working-directory: services/webapp/
      - run: npm run build
        working-directory: services/webapp/
  CI-dockerfile-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make lint-dockerfile

  CD-Tag:
    runs-on: ubuntu-20.04
    needs: [CI-api-tests, CI-webapp-tests, CI-dockerfile-tests]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Auto increment tag
        id: tag
        uses: sophiware/actions-auto-increment-tag@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  CD-Publish:
    strategy:
      fail-fast: true
      matrix:
        services: [ api, webapp ]
    runs-on: ubuntu-20.04
    needs: [ CD-Tag]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push ${{ matrix.services }} Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./services/${{ matrix.services }}
          push: true
          tags: ghcr.io/sogilis/voogle-${{ matrix.services }}:latest,ghcr.io/sogilis/voogle-${{ matrix.services }}:${{ steps.tag.outputs.tag }}
