name: CI-unit-tests

on: [push]

permissions:
  contents: read

jobs:
  api-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        name: API lint
        with:
          version: v1.29
          working-directory: services/api/
      - uses: actions/setup-go@v2
        name: Install golang 1.17.0
        with:
          go-version: "^1.17.0"
      - run: make test
        name: API unit tests
        working-directory: services/api/

  webapp-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
        working-directory: services/webapp
      - run: npm run build
        working-directory: services/webapp
  dockerfile-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make lint-dockerfile

