{
 "title": "Voogle API",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Http requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "api_http_requests_total{instance=\"api:4444\", job=\"api\", path!=\"/metrics\"}"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "api_response_status{}" }
   ]
  },
  {
   "title": "Upload Success",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_video_upload_sucess{}" },
    {
     "expr": "api_http_requests_total{instance=\"api:4444\", job=\"api\", path=\"/api/v1/videos/upload\"}"
    }
   ]
  }
 ]
}